FORMAT: 1A
HOST: https://app.fakturoid.cz/api/v2


# Fakturoid API v2 ukončeno

**API v2 bylo vypnuto 31. května 2025. Pro integraci [Fakturoidu](https://www.fakturoid.cz/) využijte API v3. Dokumentaci najdete na [www.fakturoid.cz/api/v3](https://www.fakturoid.cz/api/v3).**
